services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "443:443"
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./certs:/app/certs:ro
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
      - mysql_data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mysql_data:
